---
title: Rubyのデバッグでエラーオブジェクトのアサインを忘れた時
date: 2022-12-12
---


[CBcloud 2022アドベントカレンダー](https://qiita.com/advent-calendar/2022/cb-cloud)の12日目の記事です。

デバッグをするとき以下のように例外処理のブレイクポイントを書いて実行したとします。

```language-ruby
begin
  nil.call
rescue StandardError
  binding.irb
end
```

ここでエラーオブジェクトの変数へのアサインを忘れていることに気づきました。

そんな時は`$!`を参照しましょう。

[Rubyの仕様](https://docs.ruby-lang.org/ja/latest/method/Kernel/v/=21.html)で直近の例外を参照することができます。
